version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: v2
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.30"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: jszip
    versions:
    - 3.5.0
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: electron-is-dev
    versions:
    - 1.2.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: new-ui
  ignore:
  - dependency-name: hasha
    versions:
    - "> 5.0.0"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.50"
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: "@types/semver"
    versions:
    - 7.3.4
  - dependency-name: electron-updater
    versions:
    - 4.3.5
