
name: CI
on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:
    name: run electron-builder
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Electron Builder Action
      uses: samuelmeuli/action-electron-builder@v1.3.0
      with:
        # GitHub authentication token
        github_token: secrets.GITHUB_TOKEN
        # Whether the app should be released after a successful build
        release: true 
        # Name of the optional NPM build script which is executed before `electron-builder`
        build_script_name: build-all
